using UnityEngine;
using UnityEngine.UI;
using System.Diagnostics;
using System.IO;
using System.Collections;
using Debug = UnityEngine.Debug;
#if UNITY_EDITOR
using UnityEditor;
#endif

public class RunPythonScript : MonoBehaviour
{
    [Header("Python Setup")]
    [Tooltip("Path to the Python executable (or 'python' if it's in the PATH)")]
    public string pythonExecutablePath = "python";

    [Tooltip("Relative path from the project's parent folder")]
    public string scriptRelativePath = "tfg/blender/main.py";

    [Tooltip("Name of the .blend file generated by the Python script")]
    public string blendFileName1 = "original.blend";

    [Tooltip("Second .blend file that should also appear")]
    public string blendFileName2 = "reformed.blend";

    [Header("Loading UI")]
    [Tooltip("Assign here the Canvas or Panel used for loading")]
    [SerializeField] private GameObject loadingCanvas;

    private bool buttonUsed = false;

    private string GetProjectParentFolder()
    {
        string projectRoot = Directory.GetParent(Application.dataPath).FullName;
        return Directory.GetParent(projectRoot).FullName;
    }

    public void ExecutePythonScript()
    {
        if (buttonUsed)
        {
            Debug.LogWarning("[RunPythonScript] Floor already loaded.");
            return;
        }
        buttonUsed = true;

        loadingCanvas.SetActive(true);

        string baseFolder     = GetProjectParentFolder();
        string fullScriptPath = Path.Combine(baseFolder, scriptRelativePath).Replace('\\','/');

        Debug.Log($"[RunPythonScript] Executing: {fullScriptPath}");

        var startInfo = new ProcessStartInfo
        {
            FileName               = pythonExecutablePath,
            Arguments              = $"\"{fullScriptPath}\"",
            RedirectStandardOutput = true,
            RedirectStandardError  = true,
            UseShellExecute        = false,
            CreateNoWindow         = true
        };

        try
        {
            using (var process = Process.Start(startInfo))
            {
                process.WaitForExit();
            }
        }
        catch (System.Exception e)
        {
            Debug.LogError($"[RunPythonScript] Failed to launch Python: {e.Message}");
            loadingCanvas.SetActive(false);
            return;
        }

        StartCoroutine(CheckBlendAndRefresh());
    }

    private IEnumerator CheckBlendAndRefresh()
    {
        string resourcesFolder = Path.Combine(Application.dataPath, "Resources").Replace('\\','/');
        string blendPath1      = Path.Combine(resourcesFolder, blendFileName1).Replace('\\','/');
        string blendPath2      = Path.Combine(resourcesFolder, blendFileName2).Replace('\\','/');

        Debug.Log($"[RunPythonScript] Waiting for: {blendFileName1} and {blendFileName2}");

        float timeout = 30f;
        float elapsed = 0f;

        while (elapsed < timeout)
        {
            bool exists1 = File.Exists(blendPath1);
            bool exists2 = File.Exists(blendPath2);

            if (exists1 && exists2)
            {
                Debug.Log($"[RunPythonScript] Both .blend files found, refreshing AssetDatabase...");
#if UNITY_EDITOR
                AssetDatabase.Refresh();
#endif
                loadingCanvas.SetActive(false);
                yield break;
            }

            yield return new WaitForSeconds(1f);
            elapsed += 1f;
        }

        Debug.LogWarning($"[RunPythonScript] Both .blend files did not appear within {timeout} seconds.");
        loadingCanvas.SetActive(false);
    }
}
